name: 'Delete Deployment Environment - With rate limiting handling'
description: 'Delete the entire environment and deployments for the branch the action is running on. Based on strumwolf/delete-deployment-environment. We added rate limiting handling based on a comment from Aetherinox'
author: "jonassonn"
branding:
  icon: briefcase
  color: gray-dark
inputs:
  token:
    description: GitHub access token
    required: true
  environment:
    description: Environment to be deleted
    required: true
  ref:
    description: The `head_ref` or source branch name of the deployment to delete
    required: false
  onlyRemoveDeployments:
    description: Only remove deployments, keep the environment. Defaults to false
    required: false
  onlyDeactivateDeployments:
    description: Only inactive deployments, keep the environment and deployments. Defaults to false
    required: false
  delay:
    description: Delay in milliseconds between API calls to avoid rate limiting. Defaults to 0
    required: false
    default: '0'
runs:
  using: node20
  main: 'dist/index.js'
